# -*- coding: utf-8 -*-
"""Image_scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qIL9vobQVkpjCwvXCxJtZQD7aUO6_MLy
"""

import requests
import logging
import os
from bs4 import BeautifulSoup
from urllib.request import urlopen

save_directory = 'Images/'
if not os.path.exists(save_directory):
  os.makedirs(save_directory)

query = 'Narendra modi'
url = f'https://www.google.com/search?sca_esv=554070185&sxsrf=AB5stBhcnNJDXRbYpZxCuek01JCG5pOABw:1691246120217&q={query}&tbm=isch&source=lnms&sa=X&ved=2ahUKEwi6ouTh3sWAAxXgTWwGHW_hAtQQ0pQJegQICxAB&biw=1512&bih=828&dpr=2'

response = requests.get(url)

response

soup = BeautifulSoup(response.content,'html.parser')

image_tags = soup.find_all('img')

del image_tags[0]

len(image_tags)

for i in image_tags:
  image_url = i['src']
  image_data = requests.get(image_url).content
  with open(os.path.join(save_directory,f'{query}_{image_tags.index(i)}.jpg'),'wb') as f:
            f.write(image_data)